### ISSUE TITLE
UT Arlington and UAB are consistently under-valued by the Elo model

### ISSUE THREAD

**Issue by grdavis** [grdavis/college-basketball-elo#3]
Something must be wrong in the training data that is leading to discrepancies of 10-15 points between the Elo spread and the DraftKings line

**Comment by QuickDraw0** [comment]
UAB only shows 10 games total in the 20121101-20220303.csv data file. The scraper seems to be working but it looks like games are missing prior to Feb 2022 going back to 2010 (not just for UAB).

**Comment by grdavis** [comment]
Looks like the source (https://www.sports-reference.com/cbb/) changed how they name these two teams. They switched Alabama-Birmingham -> UAB and Texas-Arlington -> UT Arlington. So UAB and UT Arlington were considered new teams and given really low Elo ratings.

Not sure why and they might do something like this again for more teams in the future. I just did a quick find and replace in the collected data, so both should be good now.
