### ISSUE TITLE
How long for initial scrape?

### ISSUE THREAD

**Issue by ngreenberg225** [grdavis/college-basketball-elo#4]
I am trying the script on Replit and it appears to be taking forever to run the first time using `python elo.py`.

Is that normal?

**Comment by grdavis** [comment]
Hmmm that is not normal. Sometimes it takes 5-10 seconds, but usually it's 2-3. I actually think importing all the packages takes longer than the script itself. I don't know anything about Replit, but maybe it's something unique to that?

**Comment by ngreenberg225** [comment]
Perhaps. Will try it locally and see. Thanks for the response.
